name: ec2-deployment
on:
    push:
        branches:
            master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v3
            - name: docker login
              run: docker login -u ${{secrets.DOCKER_USERNANE}} -p ${{secrets.DOCKER_PWD}}
            - name: build docker image
              run: docker build -t hariharan0298/ec2-instance .
            - name: push image
              run: docker push hariharan0298/ec2-instance:latest
    deploy:
        needs: build
        runs-on: aws-ec2
        steps:
            - name: docker login
              run: docker login -u ${{secrets.DOCKER_USERNANE}} -p ${{secrets.DOCKER_PWD}}      
            - name: pull docker image
              run: sudo docker pull hariharan0298/ec2-instance:latest
            - name: run container
              run: sudo docker run -d -p 3000:80 --name reactInstanceContainer  hariharan0298/ec2-instance
